spring:
  application:
    name: messaging-app
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: b383915a1fdf670cf730
            client-secret: 5723abf6cd41c1d698b334ad3a69efed285431c0
  data:
    cassandra:
      keyspace-name: main
      username: CgpOlOdFZXXtvoxpWcjSOWLf
      password: adm.bBiL841nR63DTiL0wjTR-UKhxqAbg0tzu0L.+f5ctwXAdlSEGlBYlt9my6kO9-pPbq_Dtl.8HWA7ecUX.Qmv-RsCANKsBQQu8Ugtr99O4HT6OHrgyGm5Zu1+hkd8
      schema-action: recreate-drop-unused
      request:
        timeout: 10s
      connection: 
        connect-timeout: 10s
        init-query-timeout: 10s

astra.db:
  id: 1eb558d9-7187-4506-98be-d4e9c28addb3-1
  region: asia-south1
  keyspace: main
  application.token: AstraCS:CgpOlOdFZXXtvoxpWcjSOWLf:d0b75ed9bc34891d641be4bd2d9464dffc8514c45ed52d578f48f4da9cb3caf8

datastax.astra:
  secure-connect-bundle: secure-connect.zip